import "@/styles/globals.css";

import type { Metadata } from "next";

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="ja">
      <body>{props.children}</body>
    </html>
  );
}
