import '@/styles/globals.css';
import { Metadata } from 'next';
import React, { FC } from 'react';

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja">
      <body>{props.children}</body>
    </html>
  );
};

export default RootLayout;
